dataSources:
  master:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://127.0.0.1:3306/dianzan?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
    username: root
    password: 1234

  slave01:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://127.0.0.1:3307/dianzan?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
    username: root
    password: 1234

  slave02:
    dataSourceClassName: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    jdbcUrl: jdbc:mysql://127.0.0.1:3308/dianzan?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
    username: root
    password: 1234

rules:
  - !READWRITE_SPLITTING
    dataSourceGroups:
      rw_ds:
        writeDataSourceName: master
        readDataSourceNames:
          - slave01
          - slave02
        transactionalReadQueryStrategy: PRIMARY
        loadBalancerName: round_robin
    loadBalancers:
      round_robin:
        type: ROUND_ROBIN

  - !SHARDING
    tables:
      thumb:
        actualDataNodes: rw_ds.thumb_${0..15}
        tableStrategy:
          standard:
            shardingColumn: blog_id
            shardingAlgorithmName: thumb_mod_algo

      user_follow:
        actualDataNodes: rw_ds.user_follow_${0..15}
        tableStrategy:
          standard:
            shardingColumn: user_id
            shardingAlgorithmName: follow_dynamic_algo

    shardingAlgorithms:
      thumb_mod_algo:
        type: CLASS_BASED
        props:
          strategy: STANDARD
          algorithmClassName: com.liubinrui.config.sharding.BlogIdModShardingAlgorithm

      follow_dynamic_algo:
        type: CLASS_BASED
        props:
          strategy: STANDARD
          algorithmClassName: com.liubinrui.config.sharding.DynamicFollowShardingAlgorithm

  - !SINGLE
    tables:
      - rw_ds.blog
      - rw_ds.user

props:
  sql-show: true
